version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".credo.exs",
 ".formatter.exs",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock",
 "example_compensation/.formatter.exs",
 "example_compensation/.gitignore",
 "example_compensation/mix.exs",
 "example_compensation/mix.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md",
 "example_compensation/README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Masatoshi Nishiguchi"
SPDX-License-Identifier = "CC-BY-4.0"
